name: CI Pipeline

on:
  push:
    branches:
      - main # 指定触发事件的分支，这里是 main 分支

jobs:
  run-tests:
    uses: ./.github/workflows/run-makefile.yaml
    with:
      command: test

  run-lint:
    uses: ./.github/workflows/run-makefile.yaml
    with:
      command: lint

  build-and-push:
    needs: [ run-tests, run-lint ]
    uses: ./.github/workflows/docker-publish.yaml
    secrets: inherit