name: Run MakeFile

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

env:
  TESTCONTAINERS_RYUK_DISABLED: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run make command
        run: make ${{ inputs.command }}